# Generated by Django 6.0.6 on 2026-06-13 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cliente')),
                ('nit', models.CharField(max_length=100, unique=True, verbose_name='NIT')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contacto')),
                ('email', models.CharField(max_length=50, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='SampleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_prefix', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de muestra',
                'verbose_name_plural': 'Categoria de muestras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('manufacturing_date', models.DateField(verbose_name='Fecha de fabricación')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('quantity', models.CharField(max_length=100, verbose_name='Cantidad de muestra')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('TESTING', 'En análisis'), ('REVISION', 'En revisión'), ('APPROVAL', 'En aprobación'), ('ENDED', 'Finalizado')], default='RECEIVED', max_length=25, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.client')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.samplecategory')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
            },
        ),
        migrations.CreateModel(
            name='SampleTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(verbose_name='Evento')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Hora')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_logs', to='samples.sample')),
                ('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trazabilidad de la muestra',
                'ordering': ['-time'],
            },
        ),
    ]
