# Generated by Django 6.0.6 on 2026-06-16 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de muestra',
                'verbose_name_plural': 'Tipo de muestras',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_type',
        ),
        migrations.AlterModelOptions(
            name='sampletraceability',
            options={'ordering': ['-event_date'], 'verbose_name': 'Trazabilidad de la muestra'},
        ),
        migrations.RemoveField(
            model_name='sampletraceability',
            name='time',
        ),
        migrations.AddField(
            model_name='sampletraceability',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.sampletype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SampleCategory',
        ),
    ]
