# Generated by Django 6.0.6 on 2026-06-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sampletype_remove_sample_sample_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-received_date'], 'verbose_name': 'Muestra', 'verbose_name_plural': 'Muestras'},
        ),
    ]
