# Generated by Django 6.0.6 on 2026-06-22 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('samples', '0003_alter_client_options_alter_sample_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='sampletraceability',
            name='user_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_actions_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
