# Generated by Django 6.0.6 on 2026-07-01 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0004_alter_sample_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ensayo')),
                ('category', models.CharField(choices=[('MICROBIOLOGY', 'Microbiología'), ('PHYSICOCHEMICAL', 'Fisicoquímico')], default='MICROBIOLOGY', max_length=25, verbose_name='Categoria')),
                ('methodology', models.CharField(max_length=50, unique=True, verbose_name='Metodología')),
                ('normative_reference', models.CharField(max_length=50, verbose_name='Referencia normativa')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ensayos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssayTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(verbose_name='Evento')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_logs', to='assays.assay')),
                ('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assay_actions_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trazabilidad de la muestra',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='SampleAssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100, verbose_name='Especificación')),
                ('units', models.CharField(max_length=100, verbose_name='Unidades')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_assays', to='assays.assay')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_assays', to='samples.sample')),
            ],
            options={
                'verbose_name': 'ensayos de muestra',
                'unique_together': {('sample', 'assay')},
            },
        ),
    ]
