# Generated by Django 6.0.6 on 2026-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cliente')),
                ('nit', models.CharField(max_length=100, unique=True, verbose_name='NIT')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contacto')),
                ('email', models.CharField(max_length=50, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
