# Generated by Django 6.0.6 on 2026-06-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(verbose_name='Evento')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_logs', to='clients.client')),
                ('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_actions_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trazabilidad de clientes',
                'ordering': ['-event_date'],
            },
        ),
    ]
