# Generated by Django 6.0.6 on 2026-06-21 23:38

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('identification', models.CharField(max_length=50, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(max_length=50, verbose_name='correo')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='Nombre de usuario')),
                ('job_title', models.CharField(max_length=80, verbose_name='Cargo')),
                ('rol', models.CharField(choices=[('ASSISTANT', 'Asistente técnico'), ('AUXILIARY', 'Auxiliar'), ('LABORATORY ANALYST', 'Analista de Laboratorio'), ('QUALITY ANALYST', 'Analista de Calidad'), ('LABORATORY COORDINATOR', 'Coordinador de Laboratorio'), ('QUALITY CHIEF', 'Jefe de Calidad'), ('DIRECTOR', 'Director de Laboratorio'), ('ADMINISTRATOR', 'Administrador de Sistema')], default='ASSISTANT', verbose_name='Rol')),
                ('sign', models.ImageField(blank=True, upload_to='', verbose_name='Firma BPD')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(verbose_name='Evento')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_logs', to=settings.AUTH_USER_MODEL)),
                ('user_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trazabilidad de usuarios',
                'ordering': ['-event_date'],
            },
        ),
    ]
